### ISSUE TITLE
Last commit to master branch lost several src/ files

### ISSUE THREAD

**Issue by milktrader** [BenLauwens/SimJulia.jl#21]
c02ba17   has mysteriously lost `src/` and `src/resources` files

**Comment by BenLauwens** [comment]
This is due to a rewrite of the internals for the inclusion of the continuous time simulation and the migration to Documenter.jl. I hope to have restored all functionality by the end of the month. The previous version can be found in the release-0.3 branch.
The new code is a lot more julian and less pythonic;) JuliaCon was a big inspiration for the changes.

**Comment by milktrader** [comment]
Ok sounds good. Just wanted to make sure you're aware of it and nothing weird happened.
